# Glossary

## Common Abbreviations

### People/Parties in the Department { #DeptPeople}

-   **DGS**: [Director of Graduate Studies](#AcadLead)
    - Principal faculty member responsible for overseeing graduate program policies

-   **GPA**: [Graduate Program Advisor](#Staff)
    - Staff member tasked with advising graduate students and administering graduate policies
    
-   **MSO**:  Management Services Officer
    - Chief Administrator in the department responsible for oversight of all aspects of the program

-   **SAM**: [Student Affairs Manager](#Staff)
    - Supervisor of staff program advisors of both the graduate and undergraduate program

### Campus Entities and Terms {#Terms}

-   **ASE**: Academic Student Employee

    -   The official designation of any graduate students employed by the University (e.g. TAs)

-   **CAPS**: [Counseling & Psychological Services](https://caps.sa.ucsb.edu/)

    - Provides professional mental health service to the UCSB student body; may be a resource for assisting one of your students in distress, and may also be able to help you deal with the stresses of graduate school. All registered students are eligible for services at CAPS. 

-  **CITRAL**: [Center for Innovative Teaching, Research, and Learning](https://www.citral.ucsb.edu/)

-   **CLAS**: [Campus Learning Assistance Services](https://clas.sa.ucsb.edu/)

    -   Provides tutoring for many of the lower division classes on campus. For courses like 5A, they have regularly scheduled tutoring sessions to provide additional help for undergraduate students.
    
-  **DSP**: [Disabled Students Program](https://dsp.sa.ucsb.edu/)

- **FTE**: Full Time Equivalent

    -   Departmental budgeting is based on how many full-time employees would be needed to staff courses (eg. in Fall we have 11.75 FTE for TAs). However, ASE do not work full time. Therefore, the positions are designated 50% FTE or 25% FTE depending on whether they are 20 hours or 10 hours per week respectively.

-  **ID**: [Instructional Development](https://id.ucsb.edu/)

-  **OSC**: [Office of Student Conduct](https://studentconduct.sa.ucsb.edu/)
     - Adjudicates violations of the Student Conduct Code. In particular, they collect reports of cheating and academic dishonesty.

-  **PSTAT**: Statistics and Applied Probability

-  **UAW:** United Auto Workers (see "Union" below)

    -   <a href="https://ucsbuaw.wordpress.com/" target="_blank">**UAW 2865:**</a> The union to which all TAs, tutors, readers, and associate instructors at UCSB belong

    -   <a href="https://ucnet.universityofcalifornia.edu/labor/bargaining-units/bx/contract.html" target="_blank">The Contract Between UCSB and UAW Regarding ASEs</a>

-   **UCSB**: University of California, Santa Barbara

## Definitions of Common Terms

-   **Union:** an organized group of individuals, seeking to utilize collective bargaining power to achieve shared interests and rights in the workplace.
