# Hiring Procedures

## Teaching Assistant Applications

During the Summer before the new academic year begins, the department will send the annual Teaching Assistant Application. Graduate students who would like to be considered for a teaching assistant position must complete this form. 

Please be as detailed as possible, especially for the following sections.

+ *Workload Expectations* It is common for graduate students to work at 50\% [FTE](#Terms) which equates to 20 hours per week as well as two sections of a course. It is important for the Department to know your availability per quarter as section assignments are made. For example, if you anticipate having a Graduate Student Research position and would like to split your time between that appointment and the teaching assistant position, the department can make adjustments to your TA course assignments.

+ *Prior TA Experience* If you have been a Teaching Assistant for the PSTAT department in the past, you may list your experience here. Please list which courses in the department you have previously taught.

+ *TA/Reader Assignment Preferences* This section will allow you to indicate which courses you would like to be assigned to teach. While first choice classes may not be guaranteed, the department tries to accommodate as many preferences as possible.

+ *Other skills and qualifications* Students may list other qualifications that may be helpful when assigning TAs to courses. Additional information such as proficiency in software packages, previous graduate degrees, and passed actuarial exams would be important to note here.

The information from the Teaching Assistant Application will be used by the Director of Graduate Studies to assign graduate students to courses for the entire academic year.
You should receive information about the courses that you will be assigned at the beginning of the year. Assignments to the specific sections of their courses and finalization of the schedule will occur at the start of each quarter. You should receive this information from the [Student Affairs Manager](#Staff) (who is also the Graduate Program Advisor).


## Section Assignments

Once course assignments are completed, the [Student Affairs Manager (SAM)](#Staff) will assign TAs to sections of their course. Instructors and all teaching assistants will have the schedules communicated to them by the SAM via email before the quarter starts.

### Schedule Conflicts

If TAs have a time conflict with their assigned section, it is recommended to try to switch sections with another TA in that same course, if possible. After checking with all other TAs for the course (and the Head TA for the course, if applicable) then the next step would be to communicate with the [DGS](#AcadLead) to be switched into a different course.

### Confirming Section Assignments

If there are no conflicts with your assigned section, please confirm with the SAM that your assignment is finalized. This will trigger the SAM and [Undergraduate Program Advisors (UPA)](#Staff) to assign you to the section in GOLD and [eGrades](http://egrades.sa.ucsb.edu), which will grant you access to the course website in Canvas. In addition, your end-of-the-quarter teaching evaluations will be assigned based on what is listed in eGrades.
