# Teaching Assistant Applications

During the Summer before the new academic year begins, the department will send the annual Teaching Assistant Application. Graduate students who would like to be considered for a teaching assistant position must complete this form. 

Please be as detailed as possible, especially for the following sections.

+ *Workload Expectations* It is common for graduate students to work at 50\% full time employment (FTE) which equates to 20 hours per week as well as two sections of a course. It is important for the Department to know your availability per quarter as section assignments are made. For example, if you anticipate having a Graduate Student Research position and would like to split your time between that appointment and the teaching assistant position, the department can make adjustments to your TA course assignments.

+ *Prior TA Experience* If you have been a teaching assistant for the PSTAT department in the past, you may list your experience here. You can list which courses in the department you have previously taught.

+ *TA/Reader Assignment Preferences* This section will allow you to pick which courses you would like to be assigned to teach. While first choice classes may not be guaranteed, the department tries to accommodate as many preferences as possible.
+ *Other skills and qualifications* Students may list other qualifications that may be helpful when assigning TAs to courses. Additional information such as proficiency in software packages, previous graduate degrees, passed actuarial exams would be important to note here.

The information from the teaching assistant application will be used by the Director of Graduate Studies to assign graduate studentsto courses for the entire academic year.
You should receive information about the courses that you will be assigned at the beginning of the year. Assignments to the specific sections of their courses and finalization of the schedule will occur at the start of each quarter. You should receive this information from the Student Affairs Manager (@sec-StaffandFacultyContact).
