# Expectations for Graders

Graders (or “Readers” which is their official job title) are hired to grade student work. Typically, graders are given weekly homework papers to grade. Most often the course instructor will provide solutions to the assigned questions as well as a rubric describing how points are to be assigned in the grading. It is your responsibility to make sure that you understand the intentions of your instructor both as to what answers are considered acceptable and also how points should be distributed for partially correct answers. (See [Grading](#Grading))

## Time Cards

Unlike Teaching Assistant positions, Grader (Reader) positions are hired as hourly employees. This means that you are responsible for keeping track of the number of hours you spend each week grading papers. These hours should include any time that you spend working on solutions or understanding the material in preparation for grading. 

At the end of each pay period, Graders will need to submit a time card via the university system.
Readers will be required to report their worked hours into the <a href="https://www.timekeeping.ucsb.edu/" target="_blank">Kronos Timekeeping system</a>. Graders are on a biweekly pay period, and should receive reminders from the Kronos system to log hours and approve each timecard.  

## Time Management

Graders should work with their course Instructor to be sure that they are grading the appropriate number of hours. It is crucial that the total number of hours worked matches the amount budgeted at the end of the quarter. It is also important to note that Graders are eligible to receive tuition remission if they have at least 100 hours reported in Kronos by the end of the quarter. 

For example, If you were told that you were assigned two courses for grading 65 hours for one and 35 hours for the other, at the end of the quarter it is okay if you have worked 55 hours and 45 hours, but the total number of hours needs to be 100. You should also coordinate with the instructors of both of those courses so that they understand how you are using your time.

**Work together with your Instructor to schedule when you have grading to do**. It is often the case that there is more grading to be done in later weeks of the quarter than at the beginning. This is to be expected. You can mitigate the effects on your schedule by finishing your grading work in a timely manner. You do not want your unfinished work to build up as more homework comes in each week. Let your instructor know if there are weeks when you will be particularly busy so that they can try to schedule the grading appropriately.  Especially during finals week, you will want to plan ahead and know how much work you will be expected to do.  Leave enough space in your schedule to complete the grading on time. In the rare case that something comes up such that you do not think you will be able to complete your grading in time, make sure to communicate with the Instructor as far in advance as possible.