# Managing Conflicts as a Teaching Assistant

## Conflicts with Students

## Conflicts with Instructors

Navigating the relationship between a TA and their Instructor can be a bit delicate. On the one hand, many Instructors are your colleagues- you will be taking their classes as students, and you may even be conducting research with some of them on a one-on-one basis. However, while you are performing your duties as a TA for their class, they are still technically your “boss” or “supervisor” and should be treated with the respect that such a title commands.

The number one piece of advice we can give you is to maintain communication- we encourage you to maintain an active dialogue with your Instructor (be that through the course Discussion Board [Nectir, Discord, Slack, etc.] or through regular TA-Instructor check-ins) about your workload, as well as any unexpected issues that may arise. 

Another guiding tenet of the TA-Instructor relationship is maintaining a sense of professionalism and cohesion among the course staff. You should not publicly challenge decisions made by Instructors or your fellow TAs in front of your students- doing so degrades students’ trust in the Course Staff as a whole, which often leads to an overall sense of disarray in the course. Rather, you should handle as many of these disagreements in private (again, on Course Staff-specific Discussion Boards or meetings) as possible.

Finally, we would also like to affirm that the department is here to support you. If repeated efforts to resolve conflicts with your Instructor have been unsuccessful, please feel free to reach out to either the Graduate Advisor or Lead TA (@sec-StaffandFacultyContact) to discuss further.
