# Classroom Issues and Distressed Students


## Classroom Issues

The classroom is meant to be a place where student learning and understanding is fostered and promoted. On rare occasions, you may have a student who disrupts the learning environment with their behavior or comments. If a student exhibits disruptive behavior in the classroom, try to remain calm and ask the student to refrain from the disruptive behavior or commenting. According to the UCSB Office of Student Conduct, after notifying the student of questionable, offending, disruptive conduct and giving them the opportunity to respond and/or the opportunity to correct the behavior, an instructor may exclude from class, either temporarily or permanently, any student whose conduct is disruptive toward the instructor or other members of the class. If you need to dismiss a student from the classroom, let the Instructor know as soon as possible so that appropriate actions (e.g., formal reporting) can be taken.

## Distressed Students

UCSB is committed to providing a quality learning environment. As a TA, you may be the first to encounter a student who is in distress. Encouragement and helping the student to seek assistance with the appropriate campus and community resources are key. UCSB has multiple professionals poised to respond to distressed students. These staff members include social workers, psychologists, psychiatrists, and coordinators of student mental health services. 

The University provides a number of different resources including <a href="https://studentsindistress.sa.ucsb.edu/distressed-students-response-protocol" target="_blank">Distressed Student Response Protocols.</a> **It is important to review this material at the start of the quarter so that you know what is available if a difficult situation arises.**
