# Managing Conflicts between TAs and Instructors {#TAInstructor}

In your role as a TA, you will be working with the instructor and other TAs towards the shared goal of educating the students in the course in a supportive learning environment. Being a TA might be the first time you have interacted with a faculty member as part of an instructional team. Occasionally, you might find that navigating the relationship between a TA and their Instructor can be a bit delicate. On the one hand, instructors are your colleagues – you will be taking their classes as students, and you may even be conducting research with some of them on a one-on-one basis. On the other hand, the Instructor ultimately is in charge of the course as a whole and has the final word. Occasionally, this can help you out–if a student doesn’t agree with a policy, you can "pass the buck" to the instructor!

The number one piece of advice we can give you is to maintain communication –  we encourage you to maintain an active dialogue with your Instructor (be that through the course Discussion Board [Nectir, Discord, Slack, etc.] or through regular TA-Instructor check-ins) about your workload, as well as any unexpected issues that may arise. 

Another guiding tenet of the TA-Instructor relationship is maintaining a sense of professionalism and cohesion among the course staff. You should not publicly challenge decisions made by Instructors or your fellow TAs in front of your students – doing so degrades students’ trust in the course staff as a whole and possibly in the Instructor, which often leads to an overall sense of disarray in the course. It is important to provide the students with a "united front" as an instructional team and handle as many of these disagreements in private with the Instructor and instructional team.

Finally, we would also like to affirm that the department is here to support you. If repeated efforts to resolve conflicts with your Instructor have been unsuccessful, please feel free to reach out to the Graduate Program Advisor, the Director of Graduate Studies, the TA Training Coordinators, or the Lead TA to discuss further.

```{mermaid concerns, fig.caption="Caption"}
%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#BB2528',
      'primaryTextColor': '#fff',
      'primaryBorderColor': '#7C0000',
      'secondaryColor': 'red',
      'tertiaryColor': '#fff',
      'edgeLabelBackground': 'red'
    },
    'title': 'Node with text'
  }
}%%

flowchart TD
    linkStyle default stroke: black;
    
    title[Figure 1: There are many resources to turn to when you face a conflict.]
    title --- AA
    style title fill:#FFF,stroke:#FFF
    linkStyle 0 stroke:#FFF,stroke-width:0;
    
    AA[Student] -->|Concerns about the Course|A(Teaching Assistant)
    A -->|Course Content and Policy Issues|B(Course Instructor)
    B --> C(TA Training Coordinator)
    A --> C
    B --> D(Lead TA)
    A -->|Teaching Questions|D
    B & C & D  --> E(DGS) 
    E --> F(Department Chair)
    AA & A & D --> G(Campus Resources)
```
  