# Managing Conflicts between TAs and Students

Teaching Assistants play a key role in the structure of our courses in that you have the closest contact with individual students. Students will usually look to you first when they need help navigating a course, and they may also turn to you when they feel that something isn’t right.

## Syllabus

Many questions or complaints about a course can be addressed by pointing the student back to the syllabus for the course. A well-crafted syllabus acts as a contract between the student and the instructor which details expectations and policies. Having this agreement ensures that everyone in the course is treated fairly. The syllabus also ensures consistency across Sections in a course. Be sure to follow the policies in the syllabus for the course, bringing any questions to the Instructor. Please note that policies exist for fairness across all students in the course and that you should not make changes without consultation with the Instructor.

## Grading on Individual Assignments 

The majority of issues that students raise will be regarding the way that their assignments are graded. TAs will typically be the first contact forthat a student who goes to first when they sees something amiss in the way their work was graded. Your job is to react respectfully and carefully.
It may be as straightforward as helping the student see how their work was not correct or did not meet expectations. 

However, if you recognize that you have made a mistake in your grading of some work, then you can honestly acknowledge the mistake and make whatever correction to the grading record is necessary. Even when we are being very careful, mistakes and misunderstandings do happen. We can try to not be defensive and react like we would hope your instructors would react with you in a similar situation. If it is a mistake that you think was made consistently across many students’ work, then you should talk with your instructor about how to remediate the error.

If it appears that there was an error made in the grading done by one of your colleagues or the instructor, then you should bring this to the attention of the instructor. It is important that the grading corrections be addressed in a coordinated and consistent fashion. 

Additionally, make sure to follow any grading rubric that is provided to you by the instructor so that all students’ assignments are graded consistently. Should you have questions (e.g., partial credit), be sure to ask the instructor so that a decision can be made for the course as a whole. This is especially important when grading in Gradescope–any changes that you make to the rubric for your students propagates to all students in the course, including students with other TAs. No changes should be made to a grading rubric prior to consultation with the instructor. 

For exam grading, instructors may have specific policies about the timing and decisions about grading questions. Often, students will be required to bring up grading issues on exams right away so that there isn’t any question about alterations made to papers. Talk to your Head TA or instructor so that you know what the class policy  is. Do not make any changes to a student's exam grade without having clear permission from the course instructor.

## Overall Course Letter Grade

You may find that students who are not satisfied with their course grade come to you at the end of the quarter. They may hope to find a few more points somewhere which could push them up to the next letter, or maybe they just want to voice their frustration with the way they were evaluated.

In all cases, Teaching Assistants are not responsible for the assignment of the final letter grade in the course. This is the responsibility of the instructor. While you should still be supportive of your students, you should also let them know that the instructor is the final arbiter. Any issues with grades should be brought directly to the instructor.


## Work as a Team with your Instructor

Over the course of the quarter, you will work closely with many of the students in your sections, and you will undoubtedly be hoping that they do well in the course. It is entirely appropriate for you to advocate on behalf of your students. However, at the end of the day, the instructor is depending on you to be a part of a team. The instructor needs to be able to make decisions for the whole class and have those policies carried out consistently across sections. 

Even if you do not agree with a course policy (see Conflicts with Instructors), it is imperative that you do not criticize the course or instructor to the students. This is very harmful to the educational objectives of the course, and it will not, in the end, serve the course or your students. If you find you are not able to defend a course policy, then you need to communicate that with the instructor. They will be able to address the issues with students.

## Referring Students to the Instructor

There are many situations that students will bring to you which you will need to direct them to communicate directly with the course instructor. The instructor will want to make the decisions regarding a complex or troublesome issue from a student. It is often helpful if you let the student know the best way to bring up the issue with the instructor (e.g., email, office hours, Canvas).

If a student is angry or hostile, then directing them to the instructor can de-escalate the situation. Acknowledge the student’s concerns and redirect them to the authority of the instructor. If you are feeling unsafe, removing yourself from that situation is your first priority. You have no obligation to confront the student. You can call 911 on campus to reach campus police.

