# Teaching Supplies


## Textbooks

As a TA, you will not be expected to purchase copies of textbooks required for or utilized in courses you are TAing. Rather, the department provides rental copies of textbooks currently utilized in most of the major PSTAT courses, which are to be returned back to the department in good condition at the end of the quarter. You can contact the [Student Affairs Manager](#sec-StaffandFacultyContact) for further details on the pickup and return of these textbooks.


## Office Supplies

You will not be expected to purchase office supplies that directly relate to your teaching duties; e.g., chalk, whiteboard markers, etc. Rather, the department provides supplies like these to graduate students in the so-called "Supply Drawer", located in the PSTAT Main Office (SH 5607). Whiteboard markers need to be checked out from the Undergraduate Advisor. Please note that the office is always locked outside of business hours and also on days when the Staff are remote, so please plan accordingly.