## TA Resources

## Electronic Resources

### Canvas

Currently, UCSB utilizes **Canvas** (<a href="canvas.ucsb.edu" target="_blank">canvas.ucsb.edu</a>) as the primary learning management system on which most course sites are built. LSIT (Letters and Sciences IT) offers several resources for students and instructors who are new to the Canvas learning system at <a href = "https://help.lsit.ucsb.edu/hc/en-us/categories/5360081368475-Canvas" target="_blank">https://help.lsit.ucsb.edu/hc/en-us/categories/5360081368475-Canvas</a>; additionally, you can submit a "help ticket" for one-on-one (virtual) help using the following link: <a href="https://help.lsit.ucsb.edu/hc/en-us/requests/new?ticket_form_id=1260809796629 " target="_blank">https://help.lsit.ucsb.edu/hc/en-us/requests/new?ticket_form_id=1260809796629 </a>

### Gradescope

Many instructors also utilize Gradescope to aid in the uploading, management, and grading of student assessments. You can log in to Gradescope by navigating to <a href="http://gradescope.com/" target="_blank">http://gradescope.com/</a> and logging in with your UCSB credentials. Please note that your `@umail.ucsb.edu` address and your `@ucsb.edu` address will have separate Gradescope accounts unless you physically merge them; we encourage you to merge these accounts as soon as possible to avoid any future confusion when logging in to specific Gradescope course sites. You can find information on how to merge your Gradescope accounts at <a href="https://help.gradescope.com/article/ipjyg27lg5-student-merge-accounts" target="_blank">https://help.gradescope.com/article/ipjyg27lg5-student-merge-accounts</a>.

## Teaching Supplies

### Textbooks

As a TA, you will not be expected to purchase copies of textbooks required for or utilized in courses you are TAing. Rather, the department provides rental copies of textbooks currently utilized in most of the major PSTAT courses, which are to be returned back to the department in good condition at the end of the quarter. You can contact the [Student Affairs Manager](#sec-StaffandFacultyContact) for further details on the pickup and return of these textbooks.


### Office Supplies

You will not be expected to purchase office supplies that directly relate to your teaching duties; e.g., chalk, whiteboard markers, etc. Rather, the department provides supplies like these to graduate students in the so-called "Supply Drawer", located in the PSTAT Main Office (SH 5607). Whiteboard markers need to be checked out from the Undergraduate Advisor. Please note that the office is always locked outside of business hours and also on days when the Staff are remote, so please plan accordingly.