# Feedback From Instructors

The instructor of each course is able to give feedback both to the Teaching Assistants and to the department regarding performance of the Teaching Assistant duties. There is a Departmental Teaching Assistant Evaluation form which Instructors complete for each TA at the end of the quarter. Some of this feedback should also be sent on to the TAs.

Instructors are unlikely to have direct knowledge regarding the performance of a TA in the classroom. However, they are able to give feedback on grading and the other aspects of working together to run a course. Instructors will also often get feedback directly from students regarding sections. It can be useful for the TAs to listen to this feedback whether it is praise of a compelling teacher or concerns about the classroom.

Evaluation forms submitted by the Instructors are kept by the department. They are primarily used to find the best candidates for Head or Lead TA positions as well as Summer Teaching Associates. The evaluations also provide information to help find the best fit for a TA into a course in a future quarter.

In the assignment of TAs to sections at the start of quarter, Instructor recommendations are given a high priority. A good team of TAs and instructors leads to the best outcomes for our students. 

