# Student Evaluations

At the end of each quarter, the students will give feedback about your section via Explorance Blue (known as "Blue"). Blue is new to UCSB for Fall 2023, so more information will come out during the quarter.   These are online surveys where students answer questions about the course and about you as an instructor on a 5-point Likert scale (Strongly Agree to Strongly Disagree). The University and the Department will have a set series of questions that the students are asked, and you may be able to add custom questions. Students are also asked to provide comments about the quality of instruction in the course. Blue will be available in the last weeks of each quarter for students to complete the survey. Discuss with your Instructor whether they want you to give reminders to your students or set aside time in section for students to complete the teaching evaluations.

After the quarter has ended, you will receive the results of your teaching evaluations. Thinking carefully about the feedback is an important tool for improving your teaching. Try not to worry too much about a single negative comment, but instead try to use all of the comments and quantitative results  to understand how your students experienced the course and your teaching. Consider changes that you could make to your approach in section to address the concerns of students. It may be useful to discuss the Blue responses with your Instructor, the Teaching Assistant Training Coordinators, or Head TA if you are not sure what the feedback means.

