# Teaching Mission Statement

The Mission of the Department of Statistics and Applied Probability is, in part, to provide education and training to UCSB students in the areas of statistics, data science, actuarial science, financial mathematics, and applied probability. We seek to  educate and prepare the future workforce of data scientists and quantitative thinkers.

Our graduate students are given the opportunity to work as Teaching Assistants, Graders/Readers, and Teaching Associates in order to help further these educational goals. Our TAs work together with faculty, instructors, and colleagues to provide a broader reach to our teaching, to give additional perspective and context to classroom material, and to interact more closely with students. A Teaching Assistant position is also a key part of graduate student training in that it brings greater understanding of the key material in statistics and applied probability as well as preparing the next generation of teachers.

Our graduate students come from diverse backgrounds that strengthen our department as a whole. As stated in the <a href="https://www.pstat.ucsb.edu/" target="_blank">PSTAT homepage</a>,

> Increasing diversity across our field is essential in creating more productive, representative, and enriching outcomes as well as innovative solutions to critical problems. We recognize that, historically, the job markets and academic communities in statistical theory and methods, financial mathematics, and actuarial science have been weighted toward racial, gender, and socioeconomically privileged communities. We are dedicated to correcting this imbalance in our own community.

To this end, Teaching Assistants are encouraged to bring their own unique personal histories and perspective to their roles in ways that contribute to educating our students. They should also reach out across categories and intersectionalities to support every student who comes to our classes. 
