# Recurring Duties

## Discussion Sections

TAs hired at 50% time will be responsible for leading 2 sections per week, and TAs hired at 25% will be responsible for leading 1 section per week. Please note that for lower division courses (i.e., PSTAT 5A, PSTAT 5LS, and PSTAT 10) each section meets twice a week (so, a 50% TA in PSTAT 5A will be holding 4 x 50 = 200 minutes of section per week).

The specific duties you will be expected to carry out while leading sections often vary significantly across courses and instructors. A typical section will consist of a review portion (in which you review lecture material for your students) along with some time for students to work through a worksheet or lab activity. Certain sections, however, are led like an Office Hour and are more flexible in structure. If you are unclear about how you are expected to lead sections, please reach out to the Instructor.

Note: Please refrain from going through questions on the homework assignments prior to the due dates unless the Instructor has indicated that this is okay.


## Office Hours

Typically, TAs are expected to hold one hour of weekly Office Hours per Section led. This means that TAs appointed at 25% time usually host one (1) hour of Office Hours per week, and TAs appointed at 50% time usually host two (2) Office Hours per week. 

The Office Hour is a time when students in your discussion section can come and ask you questions about the class. This typically involves questions about the assignments. Though you are allowed to hold office hours in your cubicle/office space, you also have the option of using the following <a href="https://booked.pstat.ucsb.edu/Web/index.php?redirect=%2FWeb%2Fdashboard.php%3F" target="_blank">portal</a>) to reserve one of the following classrooms:

- South Hall 5421 (commonly referred to as the "StatLab")
- Building 434 Room 113
- Building 434 Room 126 

Please note that some courses may deviate from these norms. For example, an Instructor who provides all Section materials and homework solutions for a particular course might ask you to hold 1.5 office hours per Section instead of 1 office hour per section.

## Grading

Certain Instructors expect TAs to aid in the grading of assignments and assessments. It is typical for TAs to grade assessments that take place during Sections they lead (e.g., quizzes, worksheets, labs, etc.). As a TA, you may also be asked to grade homework assignments should the Instructor deem it necessary. It is also typical for TAs to grade exams (midterms and finals) under the guidance of the Instructor. 

Some Instructors grade using online tools (e.g.,  Gradescope, Canvas), whereas others prefer to grade on paper and in person. If your Instructor decides on in-person/synchronous grading, they (or the Head TA) will likely coordinate blocks of time for grading sessions during which you will be asked to come to campus and grade exams. Again, though, the workload asked of you should never exceed the maxima outlined in the section on Workload Expectations above. Please communicate with the Instructor and/or Head TA if you feel your grading obligations will extend your workload beyond a reasonable amount.

It is your responsibility as a TA to ensure you complete the grading of assignments and assessments by the deadlines set by the Instructor (deadlines that will often be discussed with and agreed upon by all members of the Course Staff). It is not fair to students to have to wait extended periods of time before receiving feedback on their work. Additionally, please let the Instructor know if you have any major assessments for your own classes or qualifying exams coming up that may interfere with the typical timing of grading assessments. 

## Proctoring Exams

As part of your TA duties, you may be expected to proctor exams during the quarter. Please note that even as a TA employed at 25% time you may still be asked to proctor [all]{.underline} exams for the course; the expectation is that the Instructor will modify your workload in other capacities correspondingly to ensure your workload is consistent with your official appointment.

It is the responsibility of the Instructor to provide additional information if needed regarding what specific duties are entailed in the proctoring of an exam. For in-person exams, most instructors expect proctors to maintain a vigilant eye on the students in the room, and to report any suspicious behavior to the Instructor or Head TA (if applicable) as soon as possible. Additional proctoring duties may include: distribution and collection of exams, answering of student questions during the duration of the exam, providing a headcount of students present in the exam room, etc. 

Vigilance during exam proctoring is key. While proctoring, you should not be continually on your phone, working on your own projects, or talking with other proctors. Not only is this sort of behavior counterproductive, it can also disrupt students while they are taking their exams. Rather, keep an active eye on students and follow any instructions given to you by your Instructor and/or Head TA carefully.

If timed assessments/quizzes take place during Section times, you will likely be responsible for the proctoring of these assessments. You may also be expected to aid in the creation of Section-specific assessments, as outlined in the following section of this Handbook ([Creation of Course Materials](course_materials.qmd)).
