# Grading

Certain Instructors expect TAs to aid in the grading of assignments and assessments. It is typical for TAs to be in charge of grading exams (midterms and finals), and it is also typical for TAs to be in charge of grading assessments that take place during Sections they lead (e.g. quizzes, worksheets, labs, etc.). As a TA, you may also be asked to aid in the grading of homework assignments should the Instructor deem it necessary. 

Some Instructors grade electronically (over Gradescope, Canvas, etc.), whereas others prefer to grade in-person and on paper. If your Instructor decides to grade in-person/on-paper, they (or the Head TA) will likely coordinate a series of several-hours-long sessions during which you will be asked to come to campus and grade exams. Again, though, the workload asked of you should never exceed the maxima outlined in the section on Workload Expectations above. Please communicate with the Instructor and/or Head TA if you feel your grading obligations will extend your workload beyond a reasonable amount.

It is your responsibility as a TA to ensure you complete the grading of assignments and assessments by the deadlines set by the Instructor (deadlines that will often be discussed with and agreed upon by all members of the Course Staff). It is not fair to students to have to wait extended periods of time before receiving feedback on their work.

Furthermore, you will most likely be asked to aid in the grading of Final Exams. This will necessitate you to make yourself available for a handful of grading sessions either during Final Exam week, or the week after, to be scheduled by the Instructor and/or Head TA. The Instructor will coordinate with all TAs at the start of the quarter to find a time that works for everyone- you then *must* attend the grading sessions at the agreed-upon times.