# Responsibilities of a Head TA

The primary function of a Head TA is to facilitate communication between TAs and the Instructor of the course. Head TAs are typically only assigned to very large classes such as 5A, 5LS, 10, or 120A.

If you are a TA for a course with a Head TA, it is possible that your primary means of communication with the Instructor will be through the Head TA. 

Questions regarding general course logistics should in many cases be directed to the Head TA, who may decide to include the Instructor on future communications. In many cases, the Instructor will want questions about specific student circumstances to go directly to them; however, the Instructor may ask the Head TA to be the first contact for these questions. Furthermore, weekly/regular TA meetings may be led exclusively by the Head TA in certain circumstances, though the Instructor is still expected to maintain a heavy presence in the administration of the course.

A Head TA position comes with extra responsibility, and so it is generally offered only to more senior, experienced Teaching Assistants who are familiar with the workings and logistics of that particular course. Head TAs are selected from recommendations by the instructors and the TA training team. The compensation for taking on this leadership role is a reduction in the number of sections that you will be asked to lead. If you are interested in becoming a Head TA in a future quarter, please talk to your Instructor or the [DGS](#AcadLead).

