# Discussion Sections

TAs hired at 50% time will be responsible for leading 2 sections per week, and TAs hired at 25% will be responsible for leading 1 section per week. Please note that for lower division courses (i.e., PSTAT 5A, PSTAT 5LS, and PSTAT 10) each section meets twice a week (so, a 50% TA in PSTAT 5A will be holding 4 x 50 = 200 minutes of section per week).

The specific duties you will be expected to carry out while leading sections often vary significantly across courses and instructors. A typical section will consist of a review portion (in which you review lecture material for your students) along with some time for students to work through a worksheet or lab activity. Certain sections, however, are led like an Office Hour and are more flexible in structure. If you are unclear about how you are expected to lead sections, please reach out to the Instructor.

Note: Please refrain from going through questions on the homework assignments prior to the due dates unless the Instructor has indicated that this is okay.
