# Workload Expectations

Teaching Assistants are generally hired at either 50% or 25% time. A 50% TA is responsible for two discussion sections, and a 25% TA is responsible for one discussion section. The expectation is that the workload is about 10 hours per week for each discussion section that you are responsible for. However, not every week is the same, and some weeks will be busier than others.

There are Union Rules which stipulate that TAs hired at 50% time may not be assigned work exceeding 220 hours per quarter (110 for 25% positions). Furthermore, no one can be asked to work for more than 40 hours in any given week or more than 8 hours in a given day. Additional rules and specific details are provided in <a href="https://ucnet.universityofcalifornia.edu/labor/bargaining-units/bx/docs/bx_article_32-workload_2018-2022.pdf" target="_blank">Section 32 of the amended UAW 2865 contract</a>. 

What this typically means is that you will not be asked to work in excess of 20 hours per week on a regular basis for your TA duties (10 hours if you are a 25% TA). These 20 (10) hours include time spent:

- Preparing for Sections
- Leading Sections
- Hosting Office Hours
- Attending lectures (if you are asked to do so)
- Answering student and/or Instructor emails
- Grading
- Taking attendance
- Reviewing course material and/or assessments (if applicable)

If you feel the workload being asked of you is in danger of approaching or exceeding the above-stated limits, you are encouraged to reach out to the Instructor to discuss adjusting your workload. Should discussions with the Instructor prove unsuccessful, you are encouraged to reach out to either the Graduate Student Advisor or the Lead TA to discuss further.

Please note: you are expected to prepare for each of the sections and Office Hours (OH) you lead. Above all, this entails working through any provided material (e.g. worksheets, homework, etc.) **fully** before coming into your section/OH, and ensuring you are able to answer questions about the material without having to reference the solutions. That is, you should not prepare by just skimming over the solutions provided to you- make sure you can solve all problems on your own, and that you are able to answer student questions adequately. It is unfair to your students if you come to Sections or Office Hours underprepared, especially if you are simply "reading from the solutions" and not providing any additional insight.

As a TA the notion of "business hours" can become a bit complicated, especially if you are leading a section late in the evening (be warned that some sections for courses meet from 7 - 7:50pm). It is important for your own mental health to set boundaries with regards to the times of day during which you will be working on your TA duties, and the times during which you will not. As always, the amount of work you spend on your TA duties should not exceed the maxima outlined above.

You will typically not be asked to work on weekends or holidays (though, depending on your own schedule, you may find it prudent to plan/prepare for sections over the weekend, especially if you are holding a section on Monday). Course Staff Meetings should also not be scheduled on weekends or holidays except in extreme or emergency circumstances. One exception is the initial meeting Instructors hold with their TAs- these meetings almost always occur either during break or during the weekend right before the start of the quarter. You should make every effort to be available for this meeting, just as the Instructor will make every effort to be respectful of your time and keep the meeting from running too long.

:::{.callout-tip}
Communication is key!
:::