# Absence from Section

As outlined above, one of the primary duties of a TA is to lead one or more sections of a course. It is expected that all TAs will be present for **all** Sections they are assigned throughout the quarter, unless explicitly instructed otherwise by the Instructor. 

Inform the Instructor of the course as soon as you know that you have a planned absence (i.e., if you know in advance that you will be unable to host sections on a particular set of day(s)) during the quarter. In such a situation, you should start by reaching out to the other TAs in the course for which you are a TA, to see if any of them are able to cover for you. If that proves unsuccessful, you should reach out to the Instructor to discuss. Do **NOT** simply call a friend to substitute for you or cancel section without receiving prior approval from the Instructor. 

You should also **not** simply make one of your Sections remote (i.e., over Zoom) without the Instructor's prior approval (unless your course has a PSTAT**W** designation; e.g., PSTATW 120A, PSTATW 160A, etc., as PSTATW-courses are designed for majority-remote instruction). The university has set policies in place limiting the amount of remote instruction that may legally be conducted, and this includes limiting the number of sections that can be conducted remotely.

Please note that if you fail to lead any of your assigned sections, or unexpectedly cancel/make a section remote without prior Instructor approval, your TA appointment may be terminated after review by the department. It is the responsibility of all TAs to ensure students are receiving proper attention and instruction.