# Supporting Academic Honesty

Students at UCSB have a Student Conduct Code that exists to support the highest standards of social and academic behavior and ensure an environment conducive to student learning. It is expected that students attending UCSB understand and subscribe to the ideal of academic integrity, and are willing to bear individual responsibility for their work. Any submission that fulfills an academic requirement must represent a student's original work. Any act of academic dishonesty will subject a person to University disciplinary action.

Academic dishonesty can include but is not limited to cheating, plagiarism, furnishing false information, unauthorized collaboration, and misuse of course materials. For specific examples of these categories, visit <a href="https://studentconduct.sa.ucsb.edu/academic-integrity" target="_blank">https://studentconduct.sa.ucsb.edu/academic-integrity</a>.

If you suspect a student of violating the UCSB Student Conduct Code in some way, let the Instructor of the course know as soon as possible so that appropriate actions can be taken. 
