# Preserving Student Confidentiality

As a TA, you are privy to information about students' grades in the course. This information is protected by the Family Educational Rights and Privacy Act (FERPA), a federal law designed to, among other things, protect the privacy of education records. Under FERPA, you may not disclose personally identifiable information about students nor permit anyone else (e.g., parents, other TAs) to have access to student records without written consent from the student. 

In addition to information about student grades, you may also have information about mental health, medical status, whether or not a student is documented, whether or not a student works with DSP, etc. This information is also confidential and should not be shared with or made available to anyone other than the Instructor for the course and yourself.

Here are some ways that you can preserve the confidentiality of your students:

- Ensure that physical documents containing sensitive student information (e.g., grades, Perm \#s) are kept secured and not left in public areas (e.g., mailroom, printer, hallway).

- Be sure to password-protect your computer so that others cannot access sensitive student information

- Be sure to communicate with students using their UCSB email address only

- Only share information about students with the Instructor for the course
