# Department and University Policies

## Absence from Section

As outlined above, one of the primary duties of a TA is to lead one or more sections of a course. It is expected that all TAs will be present for **all** Sections they are assigned throughout the quarter, unless explicitly instructed otherwise by the Instructor. 

Inform the Instructor of the course as soon as you know that you have a planned absence (i.e., if you know in advance that you will be unable to host sections on a particular set of day(s)) during the quarter. In such a situation, you should start by reaching out to the other TAs in the course for which you are a TA, to see if any of them are able to cover for you. If that proves unsuccessful, you should reach out to the Instructor to discuss. Do **NOT** simply call a friend to substitute for you or cancel section without receiving prior approval from the Instructor. 

You should also **not** simply make one of your Sections remote (i.e., over Zoom) without the Instructor's prior approval (unless your course has a PSTAT**W** designation; e.g., PSTATW 120A, PSTATW 160A, etc., as PSTATW-courses are designed for majority-remote instruction). The university has set policies in place limiting the amount of remote instruction that may legally be conducted, and this includes limiting the number of sections that can be conducted remotely.

Please note that if you fail to lead any of your assigned sections, or unexpectedly cancel/make a section remote without prior Instructor approval, your TA appointment may be terminated after review by the department. It is the responsibility of all TAs to ensure students are receiving proper attention and instruction.


## Preserving Student Confidentiality

As a TA, you are privy to information about students' grades in the course. This information is protected by the Family Educational Rights and Privacy Act (FERPA), a federal law designed to, among other things, protect the privacy of education records. Under FERPA, you may not disclose personally identifiable information about students nor permit anyone else (e.g., parents, other TAs) to have access to student records without written consent from the student. 

In addition to information about student grades, you may also have information about mental health, medical status, whether or not a student is documented, whether or not a student works with DSP, etc. This information is also confidential and should not be shared with or made available to anyone other than the Instructor for the course and yourself.

Here are some ways that you can preserve the confidentiality of your students:

- Ensure that physical documents containing sensitive student information (e.g., grades, Perm \#s) are kept secured and not left in public areas (e.g., mailroom, printer, hallway).

- Be sure to password-protect your computer so that others cannot access sensitive student information

- Be sure to communicate with students using their UCSB email address only

- Only share information about students with the Instructor for the course


## # Prevention of Sexual and Gender-Based Harrassment

The University of California is committed to maintaining a community dedicated to the advancement, application and transmission of knowledge and creative endeavors through academic excellence, where all people who participate in University programs and activities can work and learn together in an atmosphere free of harassment, exploitation, or intimidation.

Sexual violence, sexual harassment, gender-based harassment, and retaliation interfere with those goals. Any reports of such conduct will be responded to promptly and effectively. This includes action to stop, prevent, correct, and when necessary, discipline, behavior that violates this Policy.

You will learn more about this policy through the required training modules you will complete each academic year. The training provided has been customized for graduate students and includes information about your role as a Responsible Employee when you are a TA. In your first academic year, you will complete Campus Clarity's "Think About It: Graduate Students". Graduate students who have completed this training are assigned the "Think About It: Continuing Students" course during each subsequent year.

Should you have any questions about how to handle sexual or gender-based harassment, feel free to contact the TA Training Coordinators.

## Supporting Academic Honesty

Students at UCSB have a Student Conduct Code that exists to support the highest standards of social and academic behavior and ensure an environment conducive to student learning. It is expected that students attending UCSB understand and subscribe to the ideal of academic integrity, and are willing to bear individual responsibility for their work. Any submission that fulfills an academic requirement must represent a student's original work. Any act of academic dishonesty will subject a person to University disciplinary action.

Academic dishonesty can include but is not limited to cheating, plagiarism, furnishing false information, unauthorized collaboration, and misuse of course materials. For specific examples of these categories, visit <a href="https://studentconduct.sa.ucsb.edu/academic-integrity" target="_blank">https://studentconduct.sa.ucsb.edu/academic-integrity</a>.

If you suspect a student of violating the UCSB Student Conduct Code in some way, let the Instructor of the course know as soon as possible so that appropriate actions can be taken. 

