# Prevention of Sexual and Gender-Based Harrassment

The University of California is committed to maintaining a community dedicated to the advancement, application and transmission of knowledge and creative endeavors through academic excellence, where all people who participate in University programs and activities can work and learn together in an atmosphere free of harassment, exploitation, or intimidation.

Sexual violence, sexual harassment, gender-based harassment, and retaliation interfere with those goals. Any reports of such conduct will be responded to promptly and effectively. This includes action to stop, prevent, correct, and when necessary, discipline, behavior that violates this Policy.

You will learn more about this policy through the required training modules you will complete each academic year. The training provided has been customized for graduate students and includes information about your role as a Responsible Employee when you are a TA. In your first academic year, you will complete Campus Clarity's "Think About It: Graduate Students". Graduate students who have completed this training are assigned the "Think About It: Continuing Students" course during each subsequent year.

Should you have any questions about how to handle sexual or gender-based harassment, feel free to contact the TA Training Coordinators.
